version: "3.3"
services:

  backend:
    image: $CI_REGISTRY_IMAGE/sausage-backend:latest
    container_name: sausage-store
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      REPORT_PATH: /app/log/reports
      LOG_PATH: /app/logs
      SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
      SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
      SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL



  backend-report:
    image: $CI_REGISTRY_IMAGE/sausage-backend-report:latest
    container_name: backend-report
    restart: always
    environment:
      PORT: 8001
      DB: $SPRING_DATA_MONGODB_URI


  frontend:
    image: $CI_REGISTRY_IMAGE/sausage-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      VIRTUAL_PORT: "8080"
